# Module 3: Data Center Project - Python Execution

<a target="_blank" href="https://colab.research.google.com/github/yalinli2/EnvEtools/blob/main/course_modules/3_Data_Center_Project_Python.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

<a target="_blank" href="https:///mybinder.org/v2/gh/yalinli2/EnvEtools/main?urlpath=%2Fdoc%2Ftree%2Fcourse_modules%2F3_Data_Center_Project_Python.ipynb">
  <img src="https://mybinder.org/badge_logo.svg" alt="Open In Binder"/>
</a>

## Example Workflow
* Import data center information from [Data Center Map](www.datacentermap.com) (Excel, MATLAB, Python).
* Clean-up/extract addresses (Excel, MATLAB, Python).
* Download and extract drought data from [Drought Monitor](https://droughtmonitor.unl.edu) (Excel, MATLAB, Python).
* Download and extract electricity generation and emission data from [eGRID](https://www.epa.gov/egrid/detailed-data) (Excel, MATLAB, Python).
* Superimpose data center location and water/energy data (GIS, tableau).

## Collect Data Center Information

### Download Data

If you observe the link url closely, you can find they follow the pattern of

https://www.datacentermap.com/usa/{state}/{location}/

For example, 

https://www.datacentermap.com/usa/new-jersey/secaucus/

So we can relatively pull the data for all locations in a certain state. I will use NJ as the example for the demonstration.

### Compile Data

Once we have all data downloaded, we can use Python to compile and extract the information we want.

In [1]:
# Import the Excel
import pandas as pd
path = '../data/3_DataCenterNJtop5.xlsx'
sheet_dct = {}
datacenter = pd.read_excel(path, sheet_name=None)

In [2]:
# The imported file is a dictionary with sheet name as the keys, and sheet content as dataframes as values
datacenter

{'1_Hudson-County':                               Column1  \
 0           100 Delawanna Ave (EWR20)
 1              2 Peekay Drive (EWR21)
 2                        DataVerge NJ
 3        365 Data Centers - Carlstadt
 4        365 Data Centers - Weehawken
 5                         Equinix NY7
 6               QTS Jersey City 1 DC1
 7        Centersquare - New York EWR1
 8             11:11 Systems Carlstadt
 9                 One Evertrust Plaza
 10  Centersquare  - New York EWR2-A,B
 11   Centersquare - New York EWR2-C,D
 12                        Equinix NY6
 13           Newport Financial Center
 14                  Lumen Weehawken 1
 15                  Lumen Jersey City

                                               Column2  \
 0   Digital Realty100 Delawanna Ave07014 CliftonNe...
 1   Digital Realty2 Peekay Drive07014 CliftonNew J...
 2   DataVerge111 Town Square Place07310 Jersey Cit...
 3   365 Data Centers410 Commerce Blvd07072 Carlsta...
 4   365 Data Centers300 Boulevard East07086 Weehaw...
 5   Equinix5851 Westside Avenue07047 North BergenN...
 6   QTS Data Centers95 Christopher Columbus Dr0730...
 7   Centersquare210 Hudson Street07302 Jersey City...
 8   11:11 Systems777 Central Blvd07072 CarlstadtNe...
 9   Unknown Company1 Evertrust Plaza07302 Jersey C...
 10  Centersquare300 JFK Blvd E07086 WeehawkenNew J...
 11  Centersquare1919 Park Ave07086 WeehawkenNew Je...
 12  Equinix105 Enterprise Avenue South7094 Secaucu...
 13  Unknown Company111 Town Square Place07310 Jers...
 14  Lumen300 Boulevard East07086 WeehawkenNew Jers...
 15  Lumen1 Evertrust Plaza07302 Jersey CityNew Jer...

                                               Column3
 0   100 Delawanna Avenue in Clifton, NJ is one of ...
 1   Digital Realty's data center at 2 Peekay Drive...
 2   DataVerge is the partner of choice when it com...
 3   Our Data Center in Carlstadt, NJ, just ten mil...
 4   EWR1 Internet Data Center - High-density racks...
 5   Equinix helps companies accelerate business pe...
 6   QTS is a leading provider of data center solut...
 7   Cyxtera Technologies combines a worldwide foot...
 8   Previously part of Sungard Availability Servic...
 9       For more information, please see the profile.
 10  Cyxtera Technologies combines a worldwide foot...
 11  Cyxtera Technologies combines a worldwide foot...
 12  New York data centre NY6 in Secaucus serves th...
 13        Please see the profile for further details.
 14  For all information regarding Products and Ser...
 15  For all information regarding Products and Ser...  ,
 '2_Piscataway':                               Column1  \
 0           3 Corporate Place (EWR11)
 1   365 S. Randolphville Road (EWR12)
 2      1115 Centennial Avenue (EWR19)
 3            CyrusOne NYM1 - Somerset
 4         Digital Fortress New Jersey
 5          DataBank EWR2 - Piscataway
 6                QTS Piscataway 1 DC1
 7               Constant Hosting PNJ1
 8                    ColoCrossing NJ1
 9      Centersquare - New York EWR3-A
 10      Hammer Piscataway Data Center
 11             ReliableSite NYC Metro
 12                       24Shells NJ1
 13               Blue Hill New Jersey

                                               Column2  \
 0   Digital Realty3 Corporate Place08854 Piscatawa...
 1   Digital Realty365 South Randolphville Road0885...
 2   Digital Realty1115 Centennial Avenue08854 Pisc...
 3   CyrusOne Data Centers800 Cottontail Ln.08873 S...
 4   Digital Fortress201 B Centennial Ave.08854 Pis...
 5   DataBank25 Corporate Place South8854 Piscatawa...
 6   QTS Data Centers101 Possumtown Rd08854 Piscata...
 7   Constant Hosting101 Possumtown Rd08854 Piscata...
 8   ColoCrossing101 Possumtown Rd.08854 Piscataway...
 9   Centersquare3 Corporate Pl08854 PiscatawayNew ...
 10  Hammer Technology Holdings15 Corporate Place S...
 11  ReliableSite101 Possumtown Rd08854 PiscatawayN...
 12  24Shells Inc101 Possumtown Rd08854 PiscatawayN...
 13  Blue Hill Data Services3434 Us-2208876 Branchb...

                                               Column3
 0   Conveniently located on I-287 in Piscataway 3 ...
 1   This 268,000 square foot facility, with 36 MW ...
 2         Please see the profile for further details.
 3   Located in Somerset, New Jersey, CyrusOne’s NY...
 4   The Piscataway data center is conveniently loc...
 5   DataBank’s EWR2 data center in central New Jer...
 6   QTS is a leading provider of data center solut...
 7   Constant® Hosting provides industry leading ho...
 8   Positioned to provide ultra-low latency to fin...
 9   Cyxtera Technologies combines a worldwide foot...
 10  High quality, inexpensive carrier neutral colo...
 11  ReliableSite New York City Metro Data Center -...
 12  24Shells.net Datacenter Facility in Piscataway...
 13  Please see the profile for further details abo...  ,
 '3_Secaucus':                            Column1  \
 0   Centersquare - New York EWR5-A
 1                      Equinix NY4
 2                      Equinix NY5
 3          CoreSite Secaucus (NY3)
 4                      Equinix NY2
 5       H5 Data Centers New Jersey
 6         Colocation America NJDC2
 7                   Evocative EWR1
 8                 InterServer TEB4
 9                 InterServer TEB2
 10            247Rack Secaucus NY2

                                               Column2  \
 0   Centersquare15 Enterprise Ave North07094 Secau...
 1   Equinix755 Secaucus Road11209 SecaucusNew Jers...
 2   Equinix800 Secaucus Rd07094 SecaucusNew Jersey...
 3   CoreSite2 Emerson Lane07094 SecaucusNew Jersey...
 4   Equinix275 Hartz Way07094 SecaucusNew Jersey, USA
 5   H5 Data Centers200B Meadowlands Pkwy07094 Seca...
 6   Colocation America275 Hartz Way07094 SecaucusN...
 7   Evocative Data Centers1 Enterprise Ave N07094 ...
 8   InterServer, Inc200 Meadowlands Pkwy07094 Seca...
 9   InterServer, Inc110 Meadowlands PKWY07094 Seca...
 10  247rack.com2 Emerson Ln07094 SecaucusNew Jerse...

                                               Column3
 0   Evoque Secaucus is the ideal location to serve...
 1   Known as Equinix NY4. Please see the profile f...
 2                                Known as Equinix NY5
 3   CoreSite’s strategic New York campus expansion...
 4   Known as Equinix IBX NY2. Please see the profi...
 5   H5 Data Centers' New Jersey data center is a T...
 6   Colocation America's NJDC2 datacenter in Secau...
 7   Evocative’s New Jersey data center offers the ...
 8   InterServer TEB4 is a state-of-the-art data ce...
 9      Datacenter providing colo & dedicated servers.
 10  Tier 3 Datacenter - CoreSite facility - Carrie...  ,
 '4_Newark':                            Column1  \
 0        410 Commerce Blvd (EWR14)
 1  DataBank EWR1 - Downtown Newark
 2                      Equinix NY1
 3                165 Halsey Street
 4       US Liquidity Center (USLC)
 5    Cogent Data Center - Franklin
 6             CoreWeave Kenilworth
 7                     Lumen Newark
 8        Crown Castle Newawk (NJ1)
 9                   Lumen Newark 1

                                              Column2  \
 0  Digital Realty410 Commerce Blvd07072 Carlstadt...
 1   DataBank165 Halsey St07102 NewarkNew Jersey, USA
 2    Equinix165 Halsey St07102 NewarkNew Jersey, USA
 3  165 Halsey Street165 Halsey Street07102 Newark...
 4  Intercontinental Exchange, Inc. (ICE)1700 MacA...
 5  Cogent Communications, Inc.254 State Highway 2...
 6  CoreWeave2000 Galloping Hill Rd, 11 Nest Drive...
 7      Lumen165 Halsey St07102 NewarkNew Jersey, USA
 8  CROWN CASTLE165 Halsey St07102 NewawkNew Jerse...
 9  Lumen504 Interchange Blvd19711 NewarkNew Jerse...

                                              Column3
 0  Please see the profile for further details abo...
 1  DataBank offer 50,000 sq. ft. of carrier-neutr...
 2  Known as Equinix IBX NY1. Please see the profi...
 3  165 Halsey Street is a dedicated 1.2M sf data ...
 4  The US Liquidity Center (USLC) Data Center, lo...
 5  Cogent's Newark Data Center provides a secure ...
 6  CoreWeave, a prominent player in the tech indu...
 7  For all information regarding Products and Ser...
 8  CROWN CASTLE is located in the area Newark, US...
 9  For all information regarding Products and Ser...  ,
 '5_Morris-County':         Column1                                            Column2  \
 0  Cologix NNJ3  Cologix200 Webro Road07054 ParsippanyNew Jerse...
 1  Cologix NNJ2  Cologix9 Wing Drive07927 Cedar KnollsNew Jerse...
 2  Cologix NNJ1  Cologix1719 Route 1007054 ParsippanyNew Jersey...
 3  Cologix NNJ4  Cologix16 Wing Drive07927 Cedar KnollsNew Jers...

                                              Column3
 0  Cologix's Parsippany, NJ data center merges hi...
 1  Built for Flexibility & Scalability, the Cedar...
 2  Flexibility & Reliability - From single rack u...
 3  Cologix's move in ready disaster recovery work...  }

In [3]:
# Let's look at the first sheet, Hudson County
hudson = datacenter['1_Hudson-County']
hudson

,Column1,Column2,Column3
0,100 Delawanna Ave (EWR20),Digital Realty100 Delawanna Ave07014 CliftonNe...,"100 Delawanna Avenue in Clifton, NJ is one of ..."
1,2 Peekay Drive (EWR21),Digital Realty2 Peekay Drive07014 CliftonNew J...,Digital Realty's data center at 2 Peekay Drive...
2,DataVerge NJ,DataVerge111 Town Square Place07310 Jersey Cit...,DataVerge is the partner of choice when it com...
3,365 Data Centers - Carlstadt,365 Data Centers410 Commerce Blvd07072 Carlsta...,"Our Data Center in Carlstadt, NJ, just ten mil..."
4,365 Data Centers - Weehawken,365 Data Centers300 Boulevard East07086 Weehaw...,EWR1 Internet Data Center - High-density racks...
5,Equinix NY7,Equinix5851 Westside Avenue07047 North BergenN...,Equinix helps companies accelerate business pe...
6,QTS Jersey City 1 DC1,QTS Data Centers95 Christopher Columbus Dr0730...,QTS is a leading provider of data center solut...
7,Centersquare - New York EWR1,Centersquare210 Hudson Street07302 Jersey City...,Cyxtera Technologies combines a worldwide foot...
8,11:11 Systems Carlstadt,11:11 Systems777 Central Blvd07072 CarlstadtNe...,Previously part of Sungard Availability Servic...
9,One Evertrust Plaza,Unknown Company1 Evertrust Plaza07302 Jersey C...,"For more information, please see the profile."
10,"Centersquare - New York EWR2-A,B",Centersquare300 JFK Blvd E07086 WeehawkenNew J...,Cyxtera Technologies combines a worldwide foot...
11,"Centersquare - New York EWR2-C,D",Centersquare1919 Park Ave07086 WeehawkenNew Je...,Cyxtera Technologies combines a worldwide foot...
12,Equinix NY6,Equinix105 Enterprise Avenue South7094 Secaucu...,New York data centre NY6 in Secaucus serves th...
13,Newport Financial Center,Unknown Company111 Town Square Place07310 Jers...,Please see the profile for further details.
14,Lumen Weehawken 1,Lumen300 Boulevard East07086 WeehawkenNew Jers...,For all information regarding Products and Ser...
15,Lumen Jersey City,Lumen1 Evertrust Plaza07302 Jersey CityNew Jer...,For all information regarding Products and Ser...

In [4]:
# Our goal is to extract the zipcode for each entry, so that we will be able to plot the data center location on a map
# We can see that Column2 has the zipcode information, but we need to extract it out
for i in hudson.Column2: print(i)

Digital Realty100 Delawanna Ave07014 CliftonNew Jersey, USA
Digital Realty2 Peekay Drive07014 CliftonNew Jersey, USA
DataVerge111 Town Square Place07310 Jersey CityNew Jersey, USA
365 Data Centers410 Commerce Blvd07072 CarlstadtNew Jersey, USA
365 Data Centers300 Boulevard East07086 WeehawkenNew Jersey, USA
Equinix5851 Westside Avenue07047 North BergenNew Jersey, USA
QTS Data Centers95 Christopher Columbus Dr07302 Jersey CityNew Jersey, USA
Centersquare210 Hudson Street07302 Jersey CityNew Jersey, USA
11:11 Systems777 Central Blvd07072 CarlstadtNew Jersey, USA
Unknown Company1 Evertrust Plaza07302 Jersey CityNew Jersey, USA
Centersquare300 JFK Blvd E07086 WeehawkenNew Jersey, USA
Centersquare1919 Park Ave07086 WeehawkenNew Jersey, USA
Equinix105 Enterprise Avenue South7094 SecaucusNew Jersey, USA
Unknown Company111 Town Square Place07310 Jersey CityNew Jersey, USA
Lumen300 Boulevard East07086 WeehawkenNew Jersey, USA
Lumen1 Evertrust Plaza07302 Jersey CityNew Jersey, USA

In [5]:
# There are many different ways to do it, my method may not be the best one
# The key thing is just to identify the patterns
# You can see that all addresses end with "New Jersey, USA", so I'll first strip that from the data
# To perform such operations, we first need to convert the data type to str
zipcodes = hudson.Column2.str.rstrip('New Jersey, USA')
for i in zipcodes: print(i)

Digital Realty100 Delawanna Ave07014 Clifton
Digital Realty2 Peekay Drive07014 Clifton
DataVerge111 Town Square Place07310 Jersey Cit
365 Data Centers410 Commerce Blvd07072 Carlstadt
365 Data Centers300 Boulevard East07086 Weehawken
Equinix5851 Westside Avenue07047 North Bergen
QTS Data Centers95 Christopher Columbus Dr07302 Jersey Cit
Centersquare210 Hudson Street07302 Jersey Cit
11:11 Systems777 Central Blvd07072 Carlstadt
Unknown Company1 Evertrust Plaza07302 Jersey Cit
Centersquare300 JFK Blvd E07086 Weehawken
Centersquare1919 Park Ave07086 Weehawken
Equinix105 Enterprise Avenue South7094 Secaucu
Unknown Company111 Town Square Place07310 Jersey Cit
Lumen300 Boulevard East07086 Weehawken
Lumen1 Evertrust Plaza07302 Jersey Cit

In [6]:
# Next, we gonna split all words that are separated by space:
zipcodes = zipcodes.str.split(' ')
for i in zipcodes: print(i)

['Digital', 'Realty100', 'Delawanna', 'Ave07014', 'Clifton']
['Digital', 'Realty2', 'Peekay', 'Drive07014', 'Clifton']
['DataVerge111', 'Town', 'Square', 'Place07310', 'Jersey', 'Cit']
['365', 'Data', 'Centers410', 'Commerce', 'Blvd07072', 'Carlstadt']
['365', 'Data', 'Centers300', 'Boulevard', 'East07086', 'Weehawken']
['Equinix5851', 'Westside', 'Avenue07047', 'North', 'Bergen']
['QTS', 'Data', 'Centers95', 'Christopher', 'Columbus', 'Dr07302', 'Jersey', 'Cit']
['Centersquare210', 'Hudson', 'Street07302', 'Jersey', 'Cit']
['11:11', 'Systems777', 'Central', 'Blvd07072', 'Carlstadt']
['Unknown', 'Company1', 'Evertrust', 'Plaza07302', 'Jersey', 'Cit']
['Centersquare300', 'JFK', 'Blvd', 'E07086', 'Weehawken']
['Centersquare1919', 'Park', 'Ave07086', 'Weehawken']
['Equinix105', 'Enterprise', 'Avenue', 'South7094', 'Secaucu']
['Unknown', 'Company111', 'Town', 'Square', 'Place07310', 'Jersey', 'Cit']
['Lumen300', 'Boulevard', 'East07086', 'Weehawken']
['Lumen1', 'Evertrust', 'Plaza07302', 'Jersey', 'Cit']

In [7]:
# We can find that the data are in the last 2 or 3 segments, so let's only keep that:
def get_last_three_elements(lst):
    return lst[-3:]
zipcodes = zipcodes.apply(get_last_three_elements) # the `apply` function applies the function to each element of the dataframe
zipcodes

0        [Delawanna, Ave07014, Clifton]
1         [Peekay, Drive07014, Clifton]
2             [Place07310, Jersey, Cit]
3      [Commerce, Blvd07072, Carlstadt]
4     [Boulevard, East07086, Weehawken]
5          [Avenue07047, North, Bergen]
6                [Dr07302, Jersey, Cit]
7            [Street07302, Jersey, Cit]
8       [Central, Blvd07072, Carlstadt]
9             [Plaza07302, Jersey, Cit]
10            [Blvd, E07086, Weehawken]
11          [Park, Ave07086, Weehawken]
12         [Avenue, South7094, Secaucu]
13            [Place07310, Jersey, Cit]
14    [Boulevard, East07086, Weehawken]
15            [Plaza07302, Jersey, Cit]
Name: Column2, dtype: object

In [8]:
# Now we can split all numeric text from string text
def split_number_from_text(lst):
    new_lst = []
    for text in lst:
        head = text.rstrip('0123456789') # find the last position of text
        tail = text[len(head):]
        new_lst.extend([head, tail])
    return new_lst
zipcodes = zipcodes.apply(split_number_from_text)
zipcodes

0        [Delawanna, , Ave, 07014, Clifton, ]
1         [Peekay, , Drive, 07014, Clifton, ]
2             [Place, 07310, Jersey, , Cit, ]
3      [Commerce, , Blvd, 07072, Carlstadt, ]
4     [Boulevard, , East, 07086, Weehawken, ]
5          [Avenue, 07047, North, , Bergen, ]
6                [Dr, 07302, Jersey, , Cit, ]
7            [Street, 07302, Jersey, , Cit, ]
8       [Central, , Blvd, 07072, Carlstadt, ]
9             [Plaza, 07302, Jersey, , Cit, ]
10            [Blvd, , E, 07086, Weehawken, ]
11          [Park, , Ave, 07086, Weehawken, ]
12         [Avenue, , South, 7094, Secaucu, ]
13            [Place, 07310, Jersey, , Cit, ]
14    [Boulevard, , East, 07086, Weehawken, ]
15            [Plaza, 07302, Jersey, , Cit, ]
Name: Column2, dtype: object

In [9]:
# Now we only keep the numeric value
def return_numbers(lst):
    for i in lst: 
        if i.isnumeric():
            return i
zipcodes = zipcodes.apply(return_numbers)
zipcodes

0     07014
1     07014
2     07310
3     07072
4     07086
5     07047
6     07302
7     07302
8     07072
9     07302
10    07086
11    07086
12     7094
13    07310
14    07086
15    07302
Name: Column2, dtype: object

In [10]:
# Almost done! The only thing is that because the zipcodes start with "0", some of the "0"s were missing.
# This could be due to the reason that when saving in a numeric format, 7094 and 07094 are the same
def add_missing_zeros(text):
    if len(text) == 4:
        return "0"+text
    else: return text[-5:]
zipcodes = zipcodes.apply(add_missing_zeros)
zipcodes

0     07014
1     07014
2     07310
3     07072
4     07086
5     07047
6     07302
7     07302
8     07072
9     07302
10    07086
11    07086
12    07094
13    07310
14    07086
15    07302
Name: Column2, dtype: object

In [11]:
# Voila! Now we need to write all of the steps into a function to process all the sheets
def extract_zipcodes(sheet):
    zipcodes = sheet.Column2.str.rstrip('New Jersey, USA')
    zipcodes = zipcodes.str.split(' ')
    zipcodes = zipcodes.apply(get_last_three_elements) # no need to redefine these small functions
    zipcodes = zipcodes.apply(split_number_from_text)
    zipcodes = zipcodes.apply(return_numbers)
    zipcodes = zipcodes.apply(add_missing_zeros)
    return zipcodes

In [13]:
# Now we extract all zipcodes
zipcode_sheets = {}
for location, sheet in datacenter.items():
    location = location.split('_')[-1] # turn "1_Hudson-County" into the nicer "Hudson-County"
    new_sheet = pd.DataFrame({
        'location': location,
        'zipcode':extract_zipcodes(sheet)
    })
    zipcode_sheets[location] = new_sheet

In [14]:
zipcode_sheets

{'Hudson-County':          location zipcode
 0   Hudson-County   07014
 1   Hudson-County   07014
 2   Hudson-County   07310
 3   Hudson-County   07072
 4   Hudson-County   07086
 5   Hudson-County   07047
 6   Hudson-County   07302
 7   Hudson-County   07302
 8   Hudson-County   07072
 9   Hudson-County   07302
 10  Hudson-County   07086
 11  Hudson-County   07086
 12  Hudson-County   07094
 13  Hudson-County   07310
 14  Hudson-County   07086
 15  Hudson-County   07302,
 'Piscataway':       location zipcode
 0   Piscataway   08854
 1   Piscataway   08854
 2   Piscataway   08854
 3   Piscataway   08873
 4   Piscataway   08854
 5   Piscataway   08854
 6   Piscataway   08854
 7   Piscataway   08854
 8   Piscataway   08854
 9   Piscataway   08854
 10  Piscataway   08854
 11  Piscataway   08854
 12  Piscataway   08854
 13  Piscataway   03434,
 'Secaucus':     location zipcode
 0   Secaucus   07094
 1   Secaucus   11209
 2   Secaucus   07094
 3   Secaucus   07094
 4   Secaucus   07094
 5   Secaucus   07094
 6   Secaucus   07094
 7   Secaucus   07094
 8   Secaucus   07094
 9   Secaucus   07094
 10  Secaucus   07094,
 'Newark':   location zipcode
 0   Newark   07072
 1   Newark   07102
 2   Newark   07102
 3   Newark   07102
 4   Newark   07430
 5   Newark   07416
 6   Newark   07033
 7   Newark   07102
 8   Newark   07102
 9   Newark   19711,
 'Morris-County':         location zipcode
 0  Morris-County   07054
 1  Morris-County   07927
 2  Morris-County   07054
 3  Morris-County   07927}

In [15]:
# We can then compile all of them into one dataframe
datacenter_df = pd.concat(zipcode_sheets.values(), ignore_index=True) # ignore_index is to re-index the dataframe, try not setting it to see what it does

In [16]:
datacenter_df.head() # `head` shows the first five rows
datacenter_df.tail() # `tail` shows the last five rows

# Note that entry 50 is actually wrong, it belongs to Neward, DE, but it's because of the mistake in the data source, so we don't fix it here.

         location zipcode
50         Newark   19711
51  Morris-County   07054
52  Morris-County   07927
53  Morris-County   07054
54  Morris-County   07927

In [17]:
# Export the data so we can use it later
datacenter_df.to_csv('../data/3_DataCenterNJtop5_processed.csv')

## Collect Drought Data

We will use drought data to represent water availability. You can easily download the drought data from [Drought Monitor](https://droughtmonitor.unl.edu).

You can use whatever data you think reasonable to indicate drought severity, for this illustrative example, because it's in NJ, I will use drought data in NJ counties for the past 5 years, which can be found under Data/Data Download/Comprehensive Statistics

<img src='../images/3_drought_monitor.png' alt='Drought Monitor'/>

In [18]:
# Import data to see what it looks like
drought = pd.read_csv('../data/3_DroughtMonitorNJ.csv')
drought.head()

,MapDate,FIPS,County,State,None,D0,D1,D2,D3,D4,ValidStart,ValidEnd,StatisticFormatID
0,20251118,34001,Atlantic County,NJ,83.92,16.08,0.0,0.0,0.0,0.0,2025-11-18,2025-11-24,2
1,20251111,34001,Atlantic County,NJ,83.92,16.08,0.0,0.0,0.0,0.0,2025-11-11,2025-11-17,2
2,20251104,34001,Atlantic County,NJ,83.87,16.13,0.0,0.0,0.0,0.0,2025-11-04,2025-11-10,2
3,20251028,34001,Atlantic County,NJ,84.84,15.16,0.0,0.0,0.0,0.0,2025-10-28,2025-11-03,2
4,20251021,34001,Atlantic County,NJ,87.91,12.09,0.0,0.0,0.0,0.0,2025-10-21,2025-10-27,2

Since there are 5 different levels (D0 doesn't mean there's no drought), let's use weighted sum as a single indicator, [Drought Severity and Coverage Index](https://droughtmonitor.unl.edu/About/AbouttheData/DSCI.aspx), to represent the total severity.

$$DSCI = D0*1+D1*2+D2*3+D3*4+D4*5$$

In [19]:
drought['DSCI'] = drought.D0*1+drought.D1*2+drought.D2*3+drought.D3*4+drought.D4*5
drought.head()

,MapDate,FIPS,County,State,None,D0,D1,D2,D3,D4,ValidStart,ValidEnd,StatisticFormatID,DSCI
0,20251118,34001,Atlantic County,NJ,83.92,16.08,0.0,0.0,0.0,0.0,2025-11-18,2025-11-24,2,16.08
1,20251111,34001,Atlantic County,NJ,83.92,16.08,0.0,0.0,0.0,0.0,2025-11-11,2025-11-17,2,16.08
2,20251104,34001,Atlantic County,NJ,83.87,16.13,0.0,0.0,0.0,0.0,2025-11-04,2025-11-10,2,16.13
3,20251028,34001,Atlantic County,NJ,84.84,15.16,0.0,0.0,0.0,0.0,2025-10-28,2025-11-03,2,15.16
4,20251021,34001,Atlantic County,NJ,87.91,12.09,0.0,0.0,0.0,0.0,2025-10-21,2025-10-27,2,12.09

In [20]:
# Since we have weekly data over 5 years, we'd like to calculate the average for each county
# First we need to get the names of all counties
counties = drought.County.unique()
counties

array(['Atlantic County', 'Bergen County', 'Burlington County',
       'Camden County', 'Cape May County', 'Cumberland County',
       'Essex County', 'Gloucester County', 'Hudson County',
       'Hunterdon County', 'Mercer County', 'Middlesex County',
       'Monmouth County', 'Morris County', 'Ocean County',
       'Passaic County', 'Salem County', 'Somerset County',
       'Sussex County', 'Union County', 'Warren County'], dtype=object)

In [21]:
# Then make a new df of all averages
FIPS = [] # Federal Information Processing Standards, we need this to identify the location
dsci_avg = []
for county in counties:
    county_data = drought[drought.County==county]
    FIPS.append(county_data.FIPS.unique()[0]) # FIPS should be the same for each county
    dsci_avg.append(county_data.DSCI.mean())

drought_avg = pd.DataFrame({
    'County': counties,
    'FIPS': FIPS,
    'DSCI': dsci_avg
})
drought_avg.head()

              County   FIPS       DSCI
0    Atlantic County  34001  75.519464
1      Bergen County  34003  55.934138
2  Burlington County  34005  55.092605
3      Camden County  34007  58.714483
4    Cape May County  34009  87.965785

In [22]:
# Save the data for later usage
drought_avg.to_csv('../data/3_DroughtMonitorNJ_processed.csv')

## Collect Electricity Data

We will use electricity data from [eGRID](https://www.epa.gov/egrid), Emissions & Generation Resource Integrated Database, by the U.S. Environmental Protection Agency (USEPA).

For the illustrative example, I downloaded [eGRID2023](https://www.epa.gov/egrid/detailed-data) here.

<img src='../images/3_egrid.png' alt='eGRID'/>

The eGRID model file is relatively complex, so it's easier to navigate in Excel.

The following information is of interest to us, all of which is in the PLNT23 sheet:
* DOE/EIA ORIS plant or facility code - for identification acorss the different sheets, in case needed
* Plant FIPS state code, Plant FIPS county code, Plant county name, Plant latitude, Plant longitude - location
* Plant annual net generation (MWh) - generated electricity
* Plant annual CO2 equivalent emissions (tons) - GHG emissions

So let's pull out these data.

In [23]:
# Read the file, it's quite large so takes some time
egrid = pd.read_excel('../data/3_egrid2023_data_rev2.xlsx', sheet_name='PLNT23')
egrid.head()

,Plant file sequence number,Data Year,Plant state abbreviation,Plant name,DOE/EIA ORIS plant or facility code,Plant transmission or distribution system owner name,Plant transmission or distribution system owner ID,Utility name,Utility ID,Plant-level sector,...,Plant geothermal generation percent (resource mix),Plant other fossil generation percent (resource mix),Plant other unknown / purchased fuel generation percent (resource mix),Plant total nonrenewables generation percent (resource mix),Plant total renewables generation percent (resource mix),Plant total nonrenewables other unknown/purchased generation percent (resource mix),Plant total nonhydro renewables generation percent (resource mix),Plant total combustion generation percent (resource mix),Plant total noncombustion generation percent (resource mix),Plant total noncombustion other unknown/purchased generation percent (resource mix)
0,SEQPLT23,YEAR,PSTATABB,PNAME,ORISPL,OPRNAME,OPRCODE,UTLSRVNM,UTLSRVID,SECTOR,...,PLGTPR,PLOFPR,PLOPPR,PLTNPR,PLTRPR,PLTOPR,PLTHPR,PLCYPR,PLCNPR,PLCOPR
1,1,2023,AK,Alakanuk,57053,"Alaska Village Elec Coop, Inc",221,"Alaska Village Elec Coop, Inc",221,Electric Utility,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2023,AK,Allison Creek Hydro,58982,"Copper Valley Elec Assn, Inc",4329,"Copper Valley Elec Assn, Inc",4329,Electric Utility,...,0,0,0,0,1,0,0,0,1,0
3,3,2023,AK,Ambler,60243,"Alaska Village Elec Coop, Inc",221,"Alaska Village Elec Coop, Inc",221,Electric Utility,...,0,0,0,1,0,0,0,1,0,0
4,4,2023,AK,Angoon,7462,"Inside Passage Elec Coop, Inc",18963,"Inside Passage Elec Coop, Inc",18963,Electric Utility,...,0,0,0,1,0,0,0,1,0,0

In [24]:
# We just need data for NJ
nj = egrid[egrid['Plant state abbreviation']=='NJ'].copy()
nj.head()

,Plant file sequence number,Data Year,Plant state abbreviation,Plant name,DOE/EIA ORIS plant or facility code,Plant transmission or distribution system owner name,Plant transmission or distribution system owner ID,Utility name,Utility ID,Plant-level sector,...,Plant geothermal generation percent (resource mix),Plant other fossil generation percent (resource mix),Plant other unknown / purchased fuel generation percent (resource mix),Plant total nonrenewables generation percent (resource mix),Plant total renewables generation percent (resource mix),Plant total nonrenewables other unknown/purchased generation percent (resource mix),Plant total nonhydro renewables generation percent (resource mix),Plant total combustion generation percent (resource mix),Plant total noncombustion generation percent (resource mix),Plant total noncombustion other unknown/purchased generation percent (resource mix)
7970,7970,2023,NJ,"10 Finderne Avenue Solar, LLC",64023,Public Service Elec & Gas Co,15477,Greenbacker Renewable Energy Corporation,60025,IPP Non-CHP,...,0,0,0,0,1,0,1,0,1,0
7971,7971,2023,NJ,"101 Carnegie Center Solar, LLC",64025,Public Service Elec & Gas Co,15477,Greenbacker Renewable Energy Corporation,60025,IPP Non-CHP,...,0,0,0,0,1,0,1,0,1,0
7972,7972,2023,NJ,12 Applegate Solar LLC,59371,Jersey Central Power & Lt Co,9726,G&S Operations LLC,62629,IPP Non-CHP,...,0,0,0,0,1,0,1,0,1,0
7973,7973,2023,NJ,145 Talmadge Solar,57458,Public Service Elec & Gas Co,15477,Avidan Energy Solutions,56777,IPP Non-CHP,...,0,0,0,0,1,0,1,0,1,0
7974,7974,2023,NJ,180 Raritan Solar,58187,Public Service Elec & Gas Co,15477,"180 Raritan Energy Solutions, LLC",58164,IPP Non-CHP,...,0,0,0,0,1,0,1,0,1,0

In [25]:
# To see all column names
for i in nj.columns: print (i)

Plant file sequence number
Data Year
Plant state abbreviation
Plant name
DOE/EIA ORIS plant or facility code
Plant transmission or distribution system owner name
Plant transmission or distribution system owner ID
Utility name
Utility ID
Plant-level sector
Balancing Authority Name
Balancing Authority Code
NERC region acronym
eGRID subregion acronym
eGRID subregion name
Plant associated ISO/RTO Territory
Plant FIPS state code
Plant FIPS county code
Plant county name
Plant latitude
Plant longitude
CAPD Program Flag
Number of units
Number of generators
Plant primary fuel
Plant primary fuel category
Flag indicating if the plant burned or generated any amount of coal
Plant capacity factor
Plant nameplate capacity (MW)
Nonbaseload Factor
Biogas/ biomass plant adjustment flag
Combined heat and power (CHP) plant adjustment flag
CHP plant useful thermal output (MMBtu)
CHP plant power to heat ratio
CHP plant electric allocation factor
Plant pumped storage flag
Plant annual heat input from combustion (MMBtu)
Plant ozone season heat input from combustion (MMBtu)
Plant total annual heat input (MMBtu)
Plant total ozone season heat input (MMBtu)
Plant annual net generation (MWh)
Plant ozone season net generation (MWh)
Plant annual nonbaseload generation (MWh)
Plant annual NOx emissions (tons)
Plant ozone season NOx emissions (tons)
Plant annual SO2 emissions (tons)
Plant annual CO2 emissions (tons)
Plant annual CH4 emissions (lbs)
Plant annual N2O emissions (lbs)
Plant annual CO2 equivalent emissions (tons)
Plant annual Hg emissions (lbs)
Plant annual NOx total output emission rate (lb/MWh)
Plant ozone season NOx total output emission rate (lb/MWh)
Plant annual SO2 total output emission rate (lb/MWh)
Plant annual CO2 total output emission rate (lb/MWh)
Plant annual CH4 total output emission rate (lb/MWh)
Plant annual N2O total output emission rate (lb/MWh)
Plant annual CO2 equivalent total output emission rate (lb/MWh)
Plant annual Hg total output emission rate (lb/MWh)
Plant annual NOx input emission rate (lb/MMBtu)
Plant ozone season NOx input emission rate (lb/MMBtu)
Plant annual SO2 input emission rate (lb/MMBtu)
Plant annual CO2 input emission rate (lb/MMBtu)
Plant annual CH4 input emission rate (lb/MMBtu)
Plant annual N2O input emission rate (lb/MMBtu)
Plant annual CO2 equivalent input emission rate (lb/MMBtu)
Plant annual Hg input emission rate (lb/MMBtu)
Plant annual NOx combustion output emission rate (lb/MWh)
Plant ozone season NOx combustion output emission rate (lb/MWh)
Plant annual SO2 combustion output emission rate (lb/MWh)
Plant annual CO2 combustion output emission rate (lb/MWh)
Plant annual CH4 combustion output emission rate (lb/MWh)
Plant annual N2O combustion output emission rate (lb/MWh)
Plant annual CO2 equivalent combustion output emission rate (lb/MWh)
Plant annual Hg combustion output emission rate (lb/MWh)
Plant unadjusted annual NOx emissions (tons)
Plant unadjusted ozone season NOx emissions (tons)
Plant unadjusted annual SO2 emissions (tons)
Plant unadjusted annual CO2 emissions (tons)
Plant unadjusted annual CH4 emissions (lbs)
Plant unadjusted annual N2O emissions (lbs)
Plant unadjusted annual CO2 equivalent emissions (tons)
Plant unadjusted annual Hg emissions (lbs)
Plant unadjusted annual heat input from combustion (MMBtu)
Plant unadjusted ozone season heat input from combustion (MMBtu)
Plant unadjusted total annual heat input (MMBtu)
Plant unadjusted total ozone season heat input (MMBtu)
Plant unadjusted annual NOx emissions source
Plant unadjusted ozone season NOx emissions source
Plant unadjusted annual SO2 emissions source
Plant unadjusted annual CO2 emissions source
Plant unadjusted annual CH4 emissions source
Plant unadjusted annual N2O emissions source
Plant unadjusted annual CO2 equivalent emissions source
Plant unadjusted annual Hg emissions source
Plant unadjusted annual heat input source
Plant unadjusted ozone season heat input source
Plant annual NOx biomass emissions (tons)
Plant ozone season NOx biomass emissions (tons)
Plant annual SO2 biomass emissions (tons)
Plant annual CO2 biomass emissions (tons)
Plant annual CH4 biomass emissions (lbs)
Plant annual N2O biomass emissions (lbs)
Plant annual CO2 equivalent biomass emissions (tons)
Plant combustion heat input CHP adjustment value (MMBtu)
Plant combustion annual ozone season heat input CHP adjustment value (MMBtu)
Plant annual NOx emissions CHP adjustment value (tons)
Plant ozone season NOx emissions CHP adjustment value (tons)
Plant annual SO2 emissions CHP adjustment value (tons)
Plant annual CO2 emissions CHP adjustment value (tons)
Plant annual CH4 emissions CHP adjustment value (lbs)
Plant annual N2O emissions CHP adjustment value (lbs)
Plant annual CO2 equivalent emissions CHP adjustement value (tons)
Plant nominal heat rate (Btu/kWh)
Plant annual coal net generation (MWh)
Plant annual oil net generation (MWh)
Plant annual gas net generation (MWh)
Plant annual nuclear net generation (MWh)
Plant annual hydro net generation (MWh)
Plant annual biomass net generation (MWh)
Plant annual wind net generation (MWh)
Plant annual solar net generation (MWh)
Plant annual geothermal net generation (MWh)
Plant annual other fossil net generation (MWh)
Plant annual other unknown/ purchased fuel net generation (MWh)
Plant annual total nonrenewables net generation (MWh)
Plant annual total renewables net generation (MWh)
Plant annual total renewables other unknown/purchased net generation (MWh)
Plant annual total nonhydro renewables net generation (MWh)
Plant annual total combustion net generation (MWh)
Plant annual total noncombustion net generation (MWh)
Plant annual total noncombustion other unknown/purchased net generation (MWh)
Plant coal generation percent (resource mix)
Plant oil generation percent (resource mix)
Plant gas generation percent (resource mix)
Plant nuclear generation percent (resource mix)
Plant hydro generation percent (resource mix)
Plant biomass generation percent (resource mix)
Plant wind generation percent (resource mix)
Plant solar generation percent (resource mix)
Plant geothermal generation percent (resource mix)
Plant other fossil generation percent (resource mix)
Plant other unknown / purchased fuel generation percent (resource mix)
Plant total nonrenewables generation percent (resource mix)
Plant total renewables generation percent (resource mix)
Plant total nonrenewables other unknown/purchased generation percent (resource mix)
Plant total nonhydro renewables generation percent (resource mix)
Plant total combustion generation percent (resource mix)
Plant total noncombustion generation percent (resource mix)
Plant total noncombustion other unknown/purchased generation percent (resource mix)

In [26]:
# Getting the data we want
egrid_processed = pd.DataFrame({
    'Code': nj['DOE/EIA ORIS plant or facility code'],
    'FIPS': nj['Plant FIPS state code']+nj['Plant FIPS county code'],
    'County': nj['Plant county name'],
    'Latitude': nj['Plant latitude'],
    'Longitude': nj['Plant longitude'],
    'Generation': nj['Plant annual net generation (MWh)'],
    'Emissions': nj['Plant annual CO2 equivalent emissions (tons)'],
})
egrid_processed.head()

       Code   FIPS     County   Latitude  Longitude Generation Emissions
7970  64023  34035   Somerset   40.55812  -74.57594       3508       NaN
7971  64025  34021     Mercer   40.32312  -74.64512       1812       NaN
7972  59371  34021     Mercer  40.200278 -74.576111       2105       NaN
7973  57458  34023  Middlesex  40.535787 -74.391268       4644       NaN
7974  58187  34023  Middlesex  40.516111     -74.34       2603       NaN

In [27]:
# We can see that a lot of the emissions are NaN,
# this is because they are powered by renewable energy, so their emissions are zero,
# we need to fill those NaN by 0
egrid_processed.fillna(0, inplace=True)
egrid_processed.head()

C:\Users\Yalin\AppData\Local\Temp\ipykernel_1876\2760074093.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  egrid_processed.fillna(0, inplace=True)

       Code   FIPS     County   Latitude  Longitude  Generation  Emissions
7970  64023  34035   Somerset  40.558120 -74.575940      3508.0        0.0
7971  64025  34021     Mercer  40.323120 -74.645120      1812.0        0.0
7972  59371  34021     Mercer  40.200278 -74.576111      2105.0        0.0
7973  57458  34023  Middlesex  40.535787 -74.391268      4644.0        0.0
7974  58187  34023  Middlesex  40.516111 -74.340000      2603.0        0.0

In [28]:
# Finally export the data
egrid_processed.to_csv('../data/3_egrid2023_data_rev2_processed.csv')

Now we are ready to illustrate all data using GIS!