# Module 3: Data Center Project - Python Execution

<a target="_blank" href="https://colab.research.google.com/github/yalinli2/EnvEtools/blob/main/course_modules/3_Data_Center_Project_Python.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

<a target="_blank" href="https:///mybinder.org/v2/gh/yalinli2/EnvEtools/main?urlpath=%2Fdoc%2Ftree%2Fcourse_modules%2F3_Data_Center_Project_Python.ipynb">
  <img src="https://mybinder.org/badge_logo.svg" alt="Open In Binder"/>
</a>

## Steps
* Import data center information from [Data Center Map](www.datacentermap.com) (Excel, MATLAB, Python).
* Clean-up/extract addresses (Excel, MATLAB, Python).
* Download and extract drought data from [Drought Monitor](https://droughtmonitor.unl.edu) (Excel, MATLAB, Python).
* Download and extract electricity generation and emission data from [eGRID](https://www.epa.gov/egrid/detailed-data) (Excel, MATLAB, Python).
* Superimpose data center location and water/energy data (GIS, tableau).

## Collect Data Center Information

### Download Data

If you observe the link url closely, you can find they follow the pattern of

https://www.datacentermap.com/usa/{state}/{location}/

For example, 

https://www.datacentermap.com/usa/new-jersey/secaucus/

So we can relatively pull the data for all locations in a certain state. I will use NJ as the example for the demonstration.

### Compile Data

Once we have all data downloaded, we can use Python to compile and extract the information we want.

In [50]:
# Import the Excel
import pandas as pd
path = '../data/3_DataCenterNJtop5.xlsx'
sheet_dct = {}
file = pd.read_excel(path, sheet_name=None)

In [13]:
# The imported file is a dictionary with sheet name as the keys, and sheet content as dataframes as values
file

{'1_Hudson-County':                               Column1  \
 0           100 Delawanna Ave (EWR20)
 1              2 Peekay Drive (EWR21)
 2                        DataVerge NJ
 3        365 Data Centers - Carlstadt
 4        365 Data Centers - Weehawken
 5                         Equinix NY7
 6               QTS Jersey City 1 DC1
 7        Centersquare - New York EWR1
 8             11:11 Systems Carlstadt
 9                 One Evertrust Plaza
 10  Centersquare  - New York EWR2-A,B
 11   Centersquare - New York EWR2-C,D
 12                        Equinix NY6
 13           Newport Financial Center
 14                  Lumen Weehawken 1
 15                  Lumen Jersey City

                                               Column2  \
 0   Digital Realty100 Delawanna Ave07014 CliftonNe...
 1   Digital Realty2 Peekay Drive07014 CliftonNew J...
 2   DataVerge111 Town Square Place07310 Jersey Cit...
 3   365 Data Centers410 Commerce Blvd07072 Carlsta...
 4   365 Data Centers300 Boulevard East07086 Weehaw...
 5   Equinix5851 Westside Avenue07047 North BergenN...
 6   QTS Data Centers95 Christopher Columbus Dr0730...
 7   Centersquare210 Hudson Street07302 Jersey City...
 8   11:11 Systems777 Central Blvd07072 CarlstadtNe...
 9   Unknown Company1 Evertrust Plaza07302 Jersey C...
 10  Centersquare300 JFK Blvd E07086 WeehawkenNew J...
 11  Centersquare1919 Park Ave07086 WeehawkenNew Je...
 12  Equinix105 Enterprise Avenue South7094 Secaucu...
 13  Unknown Company111 Town Square Place07310 Jers...
 14  Lumen300 Boulevard East07086 WeehawkenNew Jers...
 15  Lumen1 Evertrust Plaza07302 Jersey CityNew Jer...

                                               Column3
 0   100 Delawanna Avenue in Clifton, NJ is one of ...
 1   Digital Realty's data center at 2 Peekay Drive...
 2   DataVerge is the partner of choice when it com...
 3   Our Data Center in Carlstadt, NJ, just ten mil...
 4   EWR1 Internet Data Center - High-density racks...
 5   Equinix helps companies accelerate business pe...
 6   QTS is a leading provider of data center solut...
 7   Cyxtera Technologies combines a worldwide foot...
 8   Previously part of Sungard Availability Servic...
 9       For more information, please see the profile.
 10  Cyxtera Technologies combines a worldwide foot...
 11  Cyxtera Technologies combines a worldwide foot...
 12  New York data centre NY6 in Secaucus serves th...
 13        Please see the profile for further details.
 14  For all information regarding Products and Ser...
 15  For all information regarding Products and Ser...  ,
 '2_Piscataway':                               Column1  \
 0           3 Corporate Place (EWR11)
 1   365 S. Randolphville Road (EWR12)
 2      1115 Centennial Avenue (EWR19)
 3            CyrusOne NYM1 - Somerset
 4         Digital Fortress New Jersey
 5          DataBank EWR2 - Piscataway
 6                QTS Piscataway 1 DC1
 7               Constant Hosting PNJ1
 8                    ColoCrossing NJ1
 9      Centersquare - New York EWR3-A
 10      Hammer Piscataway Data Center
 11             ReliableSite NYC Metro
 12                       24Shells NJ1
 13               Blue Hill New Jersey

                                               Column2  \
 0   Digital Realty3 Corporate Place08854 Piscatawa...
 1   Digital Realty365 South Randolphville Road0885...
 2   Digital Realty1115 Centennial Avenue08854 Pisc...
 3   CyrusOne Data Centers800 Cottontail Ln.08873 S...
 4   Digital Fortress201 B Centennial Ave.08854 Pis...
 5   DataBank25 Corporate Place South8854 Piscatawa...
 6   QTS Data Centers101 Possumtown Rd08854 Piscata...
 7   Constant Hosting101 Possumtown Rd08854 Piscata...
 8   ColoCrossing101 Possumtown Rd.08854 Piscataway...
 9   Centersquare3 Corporate Pl08854 PiscatawayNew ...
 10  Hammer Technology Holdings15 Corporate Place S...
 11  ReliableSite101 Possumtown Rd08854 PiscatawayN...
 12  24Shells Inc101 Possumtown Rd08854 PiscatawayN...
 13  Blue Hill Data Services3434 Us-2208876 Branchb...

                                               Column3
 0   Conveniently located on I-287 in Piscataway 3 ...
 1   This 268,000 square foot facility, with 36 MW ...
 2         Please see the profile for further details.
 3   Located in Somerset, New Jersey, CyrusOne’s NY...
 4   The Piscataway data center is conveniently loc...
 5   DataBank’s EWR2 data center in central New Jer...
 6   QTS is a leading provider of data center solut...
 7   Constant® Hosting provides industry leading ho...
 8   Positioned to provide ultra-low latency to fin...
 9   Cyxtera Technologies combines a worldwide foot...
 10  High quality, inexpensive carrier neutral colo...
 11  ReliableSite New York City Metro Data Center -...
 12  24Shells.net Datacenter Facility in Piscataway...
 13  Please see the profile for further details abo...  ,
 '3_Secaucus':                            Column1  \
 0   Centersquare - New York EWR5-A
 1                      Equinix NY4
 2                      Equinix NY5
 3          CoreSite Secaucus (NY3)
 4                      Equinix NY2
 5       H5 Data Centers New Jersey
 6         Colocation America NJDC2
 7                   Evocative EWR1
 8                 InterServer TEB4
 9                 InterServer TEB2
 10            247Rack Secaucus NY2

                                               Column2  \
 0   Centersquare15 Enterprise Ave North07094 Secau...
 1   Equinix755 Secaucus Road11209 SecaucusNew Jers...
 2   Equinix800 Secaucus Rd07094 SecaucusNew Jersey...
 3   CoreSite2 Emerson Lane07094 SecaucusNew Jersey...
 4   Equinix275 Hartz Way07094 SecaucusNew Jersey, USA
 5   H5 Data Centers200B Meadowlands Pkwy07094 Seca...
 6   Colocation America275 Hartz Way07094 SecaucusN...
 7   Evocative Data Centers1 Enterprise Ave N07094 ...
 8   InterServer, Inc200 Meadowlands Pkwy07094 Seca...
 9   InterServer, Inc110 Meadowlands PKWY07094 Seca...
 10  247rack.com2 Emerson Ln07094 SecaucusNew Jerse...

                                               Column3
 0   Evoque Secaucus is the ideal location to serve...
 1   Known as Equinix NY4. Please see the profile f...
 2                                Known as Equinix NY5
 3   CoreSite’s strategic New York campus expansion...
 4   Known as Equinix IBX NY2. Please see the profi...
 5   H5 Data Centers' New Jersey data center is a T...
 6   Colocation America's NJDC2 datacenter in Secau...
 7   Evocative’s New Jersey data center offers the ...
 8   InterServer TEB4 is a state-of-the-art data ce...
 9      Datacenter providing colo & dedicated servers.
 10  Tier 3 Datacenter - CoreSite facility - Carrie...  ,
 '4_Newark':                            Column1  \
 0        410 Commerce Blvd (EWR14)
 1  DataBank EWR1 - Downtown Newark
 2                      Equinix NY1
 3                165 Halsey Street
 4       US Liquidity Center (USLC)
 5    Cogent Data Center - Franklin
 6             CoreWeave Kenilworth
 7                     Lumen Newark
 8        Crown Castle Newawk (NJ1)
 9                   Lumen Newark 1

                                              Column2  \
 0  Digital Realty410 Commerce Blvd07072 Carlstadt...
 1   DataBank165 Halsey St07102 NewarkNew Jersey, USA
 2    Equinix165 Halsey St07102 NewarkNew Jersey, USA
 3  165 Halsey Street165 Halsey Street07102 Newark...
 4  Intercontinental Exchange, Inc. (ICE)1700 MacA...
 5  Cogent Communications, Inc.254 State Highway 2...
 6  CoreWeave2000 Galloping Hill Rd, 11 Nest Drive...
 7      Lumen165 Halsey St07102 NewarkNew Jersey, USA
 8  CROWN CASTLE165 Halsey St07102 NewawkNew Jerse...
 9  Lumen504 Interchange Blvd19711 NewarkNew Jerse...

                                              Column3
 0  Please see the profile for further details abo...
 1  DataBank offer 50,000 sq. ft. of carrier-neutr...
 2  Known as Equinix IBX NY1. Please see the profi...
 3  165 Halsey Street is a dedicated 1.2M sf data ...
 4  The US Liquidity Center (USLC) Data Center, lo...
 5  Cogent's Newark Data Center provides a secure ...
 6  CoreWeave, a prominent player in the tech indu...
 7  For all information regarding Products and Ser...
 8  CROWN CASTLE is located in the area Newark, US...
 9  For all information regarding Products and Ser...  ,
 '5_Morris-County':         Column1                                            Column2  \
 0  Cologix NNJ3  Cologix200 Webro Road07054 ParsippanyNew Jerse...
 1  Cologix NNJ2  Cologix9 Wing Drive07927 Cedar KnollsNew Jerse...
 2  Cologix NNJ1  Cologix1719 Route 1007054 ParsippanyNew Jersey...
 3  Cologix NNJ4  Cologix16 Wing Drive07927 Cedar KnollsNew Jers...

                                              Column3
 0  Cologix's Parsippany, NJ data center merges hi...
 1  Built for Flexibility & Scalability, the Cedar...
 2  Flexibility & Reliability - From single rack u...
 3  Cologix's move in ready disaster recovery work...  }

In [51]:
# Let's look at the first sheet, Hudson County
hudson = file['1_Hudson-County']
hudson

,Column1,Column2,Column3
0,100 Delawanna Ave (EWR20),Digital Realty100 Delawanna Ave07014 CliftonNe...,"100 Delawanna Avenue in Clifton, NJ is one of ..."
1,2 Peekay Drive (EWR21),Digital Realty2 Peekay Drive07014 CliftonNew J...,Digital Realty's data center at 2 Peekay Drive...
2,DataVerge NJ,DataVerge111 Town Square Place07310 Jersey Cit...,DataVerge is the partner of choice when it com...
3,365 Data Centers - Carlstadt,365 Data Centers410 Commerce Blvd07072 Carlsta...,"Our Data Center in Carlstadt, NJ, just ten mil..."
4,365 Data Centers - Weehawken,365 Data Centers300 Boulevard East07086 Weehaw...,EWR1 Internet Data Center - High-density racks...
5,Equinix NY7,Equinix5851 Westside Avenue07047 North BergenN...,Equinix helps companies accelerate business pe...
6,QTS Jersey City 1 DC1,QTS Data Centers95 Christopher Columbus Dr0730...,QTS is a leading provider of data center solut...
7,Centersquare - New York EWR1,Centersquare210 Hudson Street07302 Jersey City...,Cyxtera Technologies combines a worldwide foot...
8,11:11 Systems Carlstadt,11:11 Systems777 Central Blvd07072 CarlstadtNe...,Previously part of Sungard Availability Servic...
9,One Evertrust Plaza,Unknown Company1 Evertrust Plaza07302 Jersey C...,"For more information, please see the profile."
10,"Centersquare - New York EWR2-A,B",Centersquare300 JFK Blvd E07086 WeehawkenNew J...,Cyxtera Technologies combines a worldwide foot...
11,"Centersquare - New York EWR2-C,D",Centersquare1919 Park Ave07086 WeehawkenNew Je...,Cyxtera Technologies combines a worldwide foot...
12,Equinix NY6,Equinix105 Enterprise Avenue South7094 Secaucu...,New York data centre NY6 in Secaucus serves th...
13,Newport Financial Center,Unknown Company111 Town Square Place07310 Jers...,Please see the profile for further details.
14,Lumen Weehawken 1,Lumen300 Boulevard East07086 WeehawkenNew Jers...,For all information regarding Products and Ser...
15,Lumen Jersey City,Lumen1 Evertrust Plaza07302 Jersey CityNew Jer...,For all information regarding Products and Ser...

In [39]:
# Our goal is to extract the zipcode for each entry, so that we will be able to plot the data center location on a map
# We can see that Column2 has the zipcode information, but we need to extract it out
for i in hudson.Column2: print(i)

Digital Realty100 Delawanna Ave07014 CliftonNew Jersey, USA
Digital Realty2 Peekay Drive07014 CliftonNew Jersey, USA
DataVerge111 Town Square Place07310 Jersey CityNew Jersey, USA
365 Data Centers410 Commerce Blvd07072 CarlstadtNew Jersey, USA
365 Data Centers300 Boulevard East07086 WeehawkenNew Jersey, USA
Equinix5851 Westside Avenue07047 North BergenNew Jersey, USA
QTS Data Centers95 Christopher Columbus Dr07302 Jersey CityNew Jersey, USA
Centersquare210 Hudson Street07302 Jersey CityNew Jersey, USA
11:11 Systems777 Central Blvd07072 CarlstadtNew Jersey, USA
Unknown Company1 Evertrust Plaza07302 Jersey CityNew Jersey, USA
Centersquare300 JFK Blvd E07086 WeehawkenNew Jersey, USA
Centersquare1919 Park Ave07086 WeehawkenNew Jersey, USA
Equinix105 Enterprise Avenue South7094 SecaucusNew Jersey, USA
Unknown Company111 Town Square Place07310 Jersey CityNew Jersey, USA
Lumen300 Boulevard East07086 WeehawkenNew Jersey, USA
Lumen1 Evertrust Plaza07302 Jersey CityNew Jersey, USA

In [52]:
# There are many different ways to do it, my method may not be the best one
# The key thing is just to identify the patterns
# You can see that all addresses end with "New Jersey, USA", so I'll first strip that from the data
# To perform such operations, we first need to convert the data type to str
zipcodes = hudson.Column2.str.rstrip('New Jersey, USA')
for i in zipcodes: print(i)

Digital Realty100 Delawanna Ave07014 Clifton
Digital Realty2 Peekay Drive07014 Clifton
DataVerge111 Town Square Place07310 Jersey Cit
365 Data Centers410 Commerce Blvd07072 Carlstadt
365 Data Centers300 Boulevard East07086 Weehawken
Equinix5851 Westside Avenue07047 North Bergen
QTS Data Centers95 Christopher Columbus Dr07302 Jersey Cit
Centersquare210 Hudson Street07302 Jersey Cit
11:11 Systems777 Central Blvd07072 Carlstadt
Unknown Company1 Evertrust Plaza07302 Jersey Cit
Centersquare300 JFK Blvd E07086 Weehawken
Centersquare1919 Park Ave07086 Weehawken
Equinix105 Enterprise Avenue South7094 Secaucu
Unknown Company111 Town Square Place07310 Jersey Cit
Lumen300 Boulevard East07086 Weehawken
Lumen1 Evertrust Plaza07302 Jersey Cit

In [53]:
# Next, we gonna split all words that are separated by space:
zipcodes = zipcodes.str.split(' ')
for i in zipcodes: print(i)

['Digital', 'Realty100', 'Delawanna', 'Ave07014', 'Clifton']
['Digital', 'Realty2', 'Peekay', 'Drive07014', 'Clifton']
['DataVerge111', 'Town', 'Square', 'Place07310', 'Jersey', 'Cit']
['365', 'Data', 'Centers410', 'Commerce', 'Blvd07072', 'Carlstadt']
['365', 'Data', 'Centers300', 'Boulevard', 'East07086', 'Weehawken']
['Equinix5851', 'Westside', 'Avenue07047', 'North', 'Bergen']
['QTS', 'Data', 'Centers95', 'Christopher', 'Columbus', 'Dr07302', 'Jersey', 'Cit']
['Centersquare210', 'Hudson', 'Street07302', 'Jersey', 'Cit']
['11:11', 'Systems777', 'Central', 'Blvd07072', 'Carlstadt']
['Unknown', 'Company1', 'Evertrust', 'Plaza07302', 'Jersey', 'Cit']
['Centersquare300', 'JFK', 'Blvd', 'E07086', 'Weehawken']
['Centersquare1919', 'Park', 'Ave07086', 'Weehawken']
['Equinix105', 'Enterprise', 'Avenue', 'South7094', 'Secaucu']
['Unknown', 'Company111', 'Town', 'Square', 'Place07310', 'Jersey', 'Cit']
['Lumen300', 'Boulevard', 'East07086', 'Weehawken']
['Lumen1', 'Evertrust', 'Plaza07302', 'Jersey', 'Cit']

In [54]:
# We can find that the data are in the last 2 or 3 segments, so let's only keep that:
def get_last_three_elements(lst):
    return lst[-3:]
zipcodes = zipcodes.apply(get_last_three_elements) # the `apply` function applies the function to each element of the dataframe
zipcodes

0        [Delawanna, Ave07014, Clifton]
1         [Peekay, Drive07014, Clifton]
2             [Place07310, Jersey, Cit]
3      [Commerce, Blvd07072, Carlstadt]
4     [Boulevard, East07086, Weehawken]
5          [Avenue07047, North, Bergen]
6                [Dr07302, Jersey, Cit]
7            [Street07302, Jersey, Cit]
8       [Central, Blvd07072, Carlstadt]
9             [Plaza07302, Jersey, Cit]
10            [Blvd, E07086, Weehawken]
11          [Park, Ave07086, Weehawken]
12         [Avenue, South7094, Secaucu]
13            [Place07310, Jersey, Cit]
14    [Boulevard, East07086, Weehawken]
15            [Plaza07302, Jersey, Cit]
Name: Column2, dtype: object

In [60]:
# Now we can split all numeric text from string text
def split_number_from_text(lst):
    new_lst = []
    for text in lst:
        head = text.rstrip('0123456789') # find the last position of text
        tail = text[len(head):]
        new_lst.extend([head, tail])
    return new_lst
zipcodes = zipcodes.apply(split_number_from_text)
zipcodes

0        [Delawanna, , Ave, 07014, Clifton, ]
1         [Peekay, , Drive, 07014, Clifton, ]
2             [Place, 07310, Jersey, , Cit, ]
3      [Commerce, , Blvd, 07072, Carlstadt, ]
4     [Boulevard, , East, 07086, Weehawken, ]
5          [Avenue, 07047, North, , Bergen, ]
6                [Dr, 07302, Jersey, , Cit, ]
7            [Street, 07302, Jersey, , Cit, ]
8       [Central, , Blvd, 07072, Carlstadt, ]
9             [Plaza, 07302, Jersey, , Cit, ]
10            [Blvd, , E, 07086, Weehawken, ]
11          [Park, , Ave, 07086, Weehawken, ]
12         [Avenue, , South, 7094, Secaucu, ]
13            [Place, 07310, Jersey, , Cit, ]
14    [Boulevard, , East, 07086, Weehawken, ]
15            [Plaza, 07302, Jersey, , Cit, ]
Name: Column2, dtype: object

In [67]:
# Now we only keep the numeric value
def return_numbers(lst):
    for i in lst: 
        if i.isnumeric():
            return i
zipcodes = zipcodes.apply(return_numbers)
zipcodes

0     07014
1     07014
2     07310
3     07072
4     07086
5     07047
6     07302
7     07302
8     07072
9     07302
10    07086
11    07086
12     7094
13    07310
14    07086
15    07302
Name: Column2, dtype: object

In [117]:
# Almost done! The only thing is that because the zipcodes start with "0", some of the "0"s were missing.
# This could be due to the reason that when saving in a numeric format, 7094 and 07094 are the same
def add_missing_zeros(text):
    if len(text) == 4:
        return "0"+text
    else: return text[-5:]
zipcodes = zipcodes.apply(add_missing_zeros)
zipcodes

0    [Webro, Road07054, Parsippan]
1       [Drive07927, Cedar, Knoll]
2      [Route, 1007054, Parsippan]
3       [Drive07927, Cedar, Knoll]
Name: Column2, dtype: object

In [129]:
# Voila! Now we need to write all of the steps into a function to process all the sheets
def extract_zipcodes(sheet):
    zipcodes = sheet.Column2.str.rstrip('New Jersey, USA')
    zipcodes = zipcodes.str.split(' ')
    zipcodes = zipcodes.apply(get_last_three_elements) # no need to redefine these small functions
    zipcodes = zipcodes.apply(split_number_from_text)
    zipcodes = zipcodes.apply(return_numbers)
    zipcodes = zipcodes.apply(add_missing_zeros)
    return zipcodes

In [130]:
# Now we extract all zipcodes
zipcode_sheets = {}
for location, sheet in file.items():
    location = location.split('_')[-1] # turn "1_Hudson-County" into the nicer "Hudson-County"
    new_sheet = pd.DataFrame({
        'location': location,
        'zipcode':extract_zipcodes(sheet)
    })
    zipcode_sheets[location] = new_sheet

In [131]:
zipcode_sheets

{'Hudson-County':          location zipcode
 0   Hudson-County   07014
 1   Hudson-County   07014
 2   Hudson-County   07310
 3   Hudson-County   07072
 4   Hudson-County   07086
 5   Hudson-County   07047
 6   Hudson-County   07302
 7   Hudson-County   07302
 8   Hudson-County   07072
 9   Hudson-County   07302
 10  Hudson-County   07086
 11  Hudson-County   07086
 12  Hudson-County   07094
 13  Hudson-County   07310
 14  Hudson-County   07086
 15  Hudson-County   07302,
 'Piscataway':       location zipcode
 0   Piscataway   08854
 1   Piscataway   08854
 2   Piscataway   08854
 3   Piscataway   08873
 4   Piscataway   08854
 5   Piscataway   08854
 6   Piscataway   08854
 7   Piscataway   08854
 8   Piscataway   08854
 9   Piscataway   08854
 10  Piscataway   08854
 11  Piscataway   08854
 12  Piscataway   08854
 13  Piscataway   03434,
 'Secaucus':     location zipcode
 0   Secaucus   07094
 1   Secaucus   11209
 2   Secaucus   07094
 3   Secaucus   07094
 4   Secaucus   07094
 5   Secaucus   07094
 6   Secaucus   07094
 7   Secaucus   07094
 8   Secaucus   07094
 9   Secaucus   07094
 10  Secaucus   07094,
 'Newark':   location zipcode
 0   Newark   07072
 1   Newark   07102
 2   Newark   07102
 3   Newark   07102
 4   Newark   07430
 5   Newark   07416
 6   Newark   07033
 7   Newark   07102
 8   Newark   07102
 9   Newark   19711,
 'Morris-County':         location zipcode
 0  Morris-County   07054
 1  Morris-County   07927
 2  Morris-County   07054
 3  Morris-County   07927}

In [135]:
# We can then compile all of them into one dataframe
df_all = pd.concat(zipcode_sheets.values(), ignore_index=True) # ignore_index is to re-index the dataframe, try not setting it to see what it does

In [141]:
df_all.head() # `head` shows the first five rows
df_all.tail() # `tail` shows the last five rows

# Note that entry 50 is actually wrong, it belongs to Neward, DE, but it's because of the mistake in the data source, so we don't fix it here.

         location zipcode
50         Newark   19711
51  Morris-County   07054
52  Morris-County   07927
53  Morris-County   07054
54  Morris-County   07927

In [142]:
# Export the data so we can use it later
df_all.to_csv('../data/3_DataCenterNJtop5_processed.csv')