# Supplementary Module 1: Python Basics

<a target="_blank" href="https://colab.research.google.com/github/yalinli2/EnvEtools/blob/main/course_modules/S1_Python_Basics.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

<a target="_blank" href="https:///mybinder.org/v2/gh/yalinli2/EnvEtools/main?urlpath=%2Fdoc%2Ftree%2Fcourse_modules%S1F2_Python_Basics.ipynb">
  <img src="https://mybinder.org/badge_logo.svg" alt="Open In Binder"/>
</a>

## Core Concepts

### Python

**Python** is a **programming language**.

It defines the rules (syntax) used to write programs.

Python allows you to perform tasks such as:
- numerical calculations
- data analysis
- automation
- scientific modeling
- machine learning

Python code be written/run in many environments, such as:

- Terminal (bash, command prompt, powershell, etc.)
- Jupyter Notebook
- Google Colab
- Development tools (integrated development environment, IDE) like VS Code or PyCharm

So **Python is the core language**, while the other tools are environments used to run Python.

### Jupyter Notebook

**Jupyter Notebook** is an **interactive environment for running Python code**.

Instead of writing one long program, code is organized into **cells**.

A notebook can contain:
- text explanations
- code
- output (tables, numbers, figures)

This format is especially useful for:
- teaching
- data analysis
- experiments
- research notebooks

Notebook files are saved as `.ipynb`

These files store both **code and formatted text**.

#### Running Python in a Notebook

A Jupyter Notebook contains **cells**:
- **Markdown cells**: text and explanation
- **Code cells**: Python code that you can run

Run a cell using:

**Shift + Enter**

### Google Colab

**Google Colab** (short for *Colaboratory*) is a **cloud version of Jupyter Notebook**.

It runs inside a **web browser** and uses **Google's servers** to execute Python code.

Advantages:

- no installation required
- easy sharing
- integrates with Google Drive
- free access to GPUs and cloud computing resources

In practice, Google Colab notebooks look almost identical to Jupyter notebooks.

### Python Script

A **Python script** is a file that contains Python code saved with the extension `.py`

Instead of running code cell-by-cell (like in a notebook), a script runs **all at once from top to bottom**.

Example script: `analysis.py`

```python
rain = [0, 5.2, 12.1, 3.4]

total_rain = sum(rain)
avg_rain = total_rain / len(rain)

print("Total rainfall:", total_rain)
print("Average rainfall:", avg_rain)

You run a Python script from a terminal or command prompt:

```
python analysis.py

### IDE (Integrated Development Environment)

An IDE is software designed to help programmers write, edit, and manage code efficiently.

An IDE typically includes:

- a code editor
- syntax highlighting
- debugging tools
- file management
- project organization
- code completion

Popular Python IDEs include:
- VS Code
- PyCharm
- Spyder

### Comparison

| Tool | What it is | Main Purpose | Typical File Type | When to Use |
|-----|-----|-----|-----|-----|
| Python | Programming language | Defines syntax and logic for programs | `.py` | Writing programs, data analysis, modeling |
| Jupyter Notebook | Interactive coding environment | Run code step-by-step with text and output | `.ipynb` | Teaching, exploration, data analysis |
| Google Colab | Cloud-hosted notebook platform | Run Jupyter notebooks in a browser | `.ipynb` | No installation, easy sharing, cloud computing |
| Python Script | File containing Python code | Execute a complete program from start to finish | `.py` | Automation, pipelines, larger programs |
| IDE (e.g., VS Code, PyCharm) | Software development environment | Write, edit, debug, and manage code projects | various | Developing larger or more complex projects |

## Variables and Basic Data Types

In [1]:
# Numbers
a = 10
b = 3.5

print(a)
print(b)
print(type(a))
print(type(b))

10
3.5
<class 'int'>
<class 'float'>

In [2]:
# Strings (text)
name = "Environmental Engineering"
print(name)
print(type(name))

Environmental Engineering
<class 'str'>

In [3]:
# Boolean values
is_valid = True
print(is_valid)
print(type(is_valid))

True
<class 'bool'>

### Basic arithmetic
Python works like a calculator.

In [4]:
x = 5
y = 2

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)   # exponent

7
3
10
2.5
25

## Containers

Python provides several container types for storing collections of data. Here we will compare:
- `list`
- `tuple`
- `dictionary`
- `set`
- `NumPy array`
- `pandas DataFrame`

### List

A **list** is the most common Python container. It stores an ordered sequence of items and can be changed after creation.

In [5]:
rain = [0, 5.2, 12.1, 3.4]

print(rain)
print("First value:", rain[0])
print("Length:", len(rain))

rain.append(7.8)
print("After append:", rain)

[0, 5.2, 12.1, 3.4]
First value: 0
Length: 4
After append: [0, 5.2, 12.1, 3.4, 7.8]

**List** is typically used for general-purpose data storage, especially when you are adding/removing elements.

### Tuple

A **tuple** is similar to a list, but it cannot be changed after creation.

In [6]:
coordinates = (40.5, -74.4)

print(coordinates)
print("First value:", coordinates[0])
print("Length:", len(coordinates))

(40.5, -74.4)
First value: 40.5
Length: 2

**Tuple** is typical uses in fixed settings.

In [7]:
list_point = [40.5, -74.4]

tuple_point = (40.5, -74.4)

In [8]:
# This works
print(list_point)
list_point[0] = 41.0 
print(list_point)

[40.5, -74.4]
[41.0, -74.4]

In [9]:
# This triggers error
print(tuple_point)
# tuple_point[0] = 41.0 
# print(tuple_point)

(40.5, -74.4)

Compared with lists, tuples are slightly:
- faster
- more memory-efficient

### Dictionary

A **dictionary** stores data as **key-value pairs**.  
It is very useful when data has labels.

In [10]:
sample = {
    "site": "River A",
    "pH": 7.2,
    "temperature_C": 20.5
}

print(sample)
print("pH:", sample["pH"])

sample["DO_mgL"] = 8.3
print("Updated dictionary:", sample)

{'site': 'River A', 'pH': 7.2, 'temperature_C': 20.5}
pH: 7.2
Updated dictionary: {'site': 'River A', 'pH': 7.2, 'temperature_C': 20.5, 'DO_mgL': 8.3}

Typical **dictionary** uses:
- sample metadata
- labeled engineering data
- lookup tables

### Set

A **set** stores unique values only.  
It is useful when duplicates should be removed or when checking whether something is present.

In [11]:
sites = {"A", "B", "C", "A"}

print(sites)
print("Is 'A' in the set?", "A" in sites)
print("Is 'D' in the set?", "D" in sites)

{'A', 'C', 'B'}
Is 'A' in the set? True
Is 'D' in the set? False

**Set** is typical used for:
- removing duplicate values
- membership testing

### Array (`numpy`)

An **array** is designed for efficient numerical computation.  
As the name indicates, it is defined in the `numpy` package, it is commonly used in scientific computing and engineering.

In [12]:
import numpy as np

flow = np.array([1.8, 2.0, 2.2, 2.4])

print(flow)
print("First value:", flow[0])
print("Mean:", np.mean(flow))
print("Flow times 1000:", flow * 1000)

[1.8 2.  2.2 2.4]
First value: 1.8
Mean: 2.1
Flow times 1000: [1800. 2000. 2200. 2400.]

In [13]:
data = np.array([1, 2, 3, 4, 5])

print(data)
print(type(data))

[1 2 3 4 5]
<class 'numpy.ndarray'>

In [14]:
# Vectorized operations
data = np.array([1, 2, 3, 4, 5])

print(data * 2)
print(data + 10)

[ 2  4  6  8 10]
[11 12 13 14 15]

In [15]:
# Basic statistics
data = np.array([1, 2, 3, 4, 5])

print("Mean:", np.mean(data))
print("Std:", np.std(data))

Mean: 3.0
Std: 1.4142135623730951

Typical uses:
- numerical vectors
- matrix operations
- scientific calculations

### DataFrame (`pandas`)

A **DataFrame** is a table-like container with labeled rows and columns.  
It is defined in the `pandas` package and is extremely useful for data analysis.

In [16]:
import pandas as pd

data = {
    "site": ["A", "B", "C"],
    "flow_m3s": [2.3, 1.1, 4.0],
    "nitrate_mgL": [3.2, 5.1, 2.8]
}

df = pd.DataFrame(data)

df

  site  flow_m3s  nitrate_mgL
0    A       2.3          3.2
1    B       1.1          5.1
2    C       4.0          2.8

In [17]:
print("Column names:", df.columns.tolist())
print("Mean flow:", df["flow_m3s"].mean())

print("\nSelect one column:")
print(df["nitrate_mgL"])

print("\nFilter rows with nitrate > 4:")
print(df[df["nitrate_mgL"] > 4])

Column names: ['site', 'flow_m3s', 'nitrate_mgL']
Mean flow: 2.466666666666667

Select one column:
0    3.2
1    5.1
2    2.8
Name: nitrate_mgL, dtype: float64

Filter rows with nitrate > 4:
  site  flow_m3s  nitrate_mgL
1    B       1.1          5.1

In [18]:
# Basic exploration
print(df.head())
print(df.describe())

  site  flow_m3s  nitrate_mgL
0    A       2.3          3.2
1    B       1.1          5.1
2    C       4.0          2.8
       flow_m3s  nitrate_mgL
count  3.000000     3.000000
mean   2.466667     3.700000
std    1.457166     1.228821
min    1.100000     2.800000
25%    1.700000     3.000000
50%    2.300000     3.200000
75%    3.150000     4.150000
max    4.000000     5.100000

In [19]:
# Column operations
df["load"] = df["flow_m3s"] * df["nitrate_mgL"]

df

  site  flow_m3s  nitrate_mgL   load
0    A       2.3          3.2   7.36
1    B       1.1          5.1   5.61
2    C       4.0          2.8  11.20

Typical uses:
- spreadsheets in Python
- environmental monitoring data
- tabular datasets with multiple columns

### Summary Table

| Container | Ordered | Mutable | Allows Duplicates | How to Access | Typical Use |
|---|---|---|---|---|---|
| **List** | Yes | Yes | Yes | Index (`x[0]`) | General-purpose sequence of items |
| **Tuple** | Yes | No | Yes | Index (`x[0]`) | Fixed collection of values |
| **Dictionary** | Yes* | Yes | Keys: No <br> Values: Yes | Key (`x["key"]`) | Labeled data / key-value pairs |
| **Set** | No | Yes | No | Membership test (`in`) | Unique values |
| **`numpy` Array** | Yes | Yes | Yes | Index (`x[0]`) | Numerical computation |
| **`pandas` DataFrame** | Yes | Yes | Yes | Column name / row-column selection | Tabular data |

\* In Python 3.7+, dictionaries preserve insertion order.

### Simplified Version

| Container | Best Simple Description |
|---|---|
| **List** | General container |
| **Tuple** | Fixed container |
| **Dictionary** | Labeled container |
| **Set** | Unique container |
| **NumPy Array** | Numerical container |
| **pandas DataFrame** | Table container |

### Rules of Thumb

- Use a **list** for a general ordered collection.
- Use a **tuple** when values should stay fixed.
- Use a **dictionary** for labeled data.
- Use a **set** for unique values.
- Use a **NumPy array** for numerical computation.
- Use a **pandas DataFrame** for tabular data.

## Functions

A **function** is a reusable block of code that performs a specific task.

Functions help make programs:
- easier to read
- easier to reuse
- easier to organize

Instead of repeating the same code many times, we can define a function once and use it whenever needed.

### Basic Syntax

A Python function is defined using the `def` keyword.

```python
def function_name(parameters):
    # code block
    return result

| Part            | Meaning                           |
| --------------- | --------------------------------- |
| `def`           | keyword used to define a function |
| `function_name` | the name of the function          |
| `parameters`    | inputs to the function            |
| `return`        | value sent back by the function   |

In [20]:
def compute_average(data):
    total = 0
    
    for v in data:
        total += v
    
    return total / len(data)

numbers = [10, 20, 30]

print(compute_average(numbers))

20.0

### `*args` and `**kwargs` in Python

Sometimes we want a function to accept **a flexible number of inputs**.  
Python provides two tools for this:

- `*args` → multiple **positional arguments**
- `**kwargs` → multiple **keyword arguments**

These allow a function to accept **any number of inputs**.

### `*args`: Multiple Positional Arguments

`*args` allows a function to receive **any number of positional arguments**.

In [21]:
# Example function:
def add_numbers(*args):
    print(args)

In [22]:
# Calling the function:
add_numbers(1, 2, 3, 4)

(1, 2, 3, 4)

In [23]:
def sum_numbers(*args):
    total = 0
    for value in args:
        total += value
    return total

sum_numbers(1, 2, 3, 4, 5)

15

In the examples above, `args` becomes a tuple containing all the arguments.

In [24]:
# `*args` collects positional inputs into a **tuple**.

def show_args(*args):
    print(type(args))
    print(args)

show_args(10, 20, 30)

<class 'tuple'>
(10, 20, 30)

### `**kwargs`: Multiple Keyword Arguments

`**kwargs` allows a function to accept **any number of keyword arguments**.

Keyword arguments have **names**.

In [25]:
# Example
def show_info(**kwargs):
    print(kwargs)

show_info(name="River A", pH=7.2, temperature=20)

{'name': 'River A', 'pH': 7.2, 'temperature': 20}

`kwargs` becomes a **dictionary**.

In [26]:
def show_info(**kwargs):
    print(type(kwargs))
    print(kwargs)

show_info(site="A", flow=2.3)

<class 'dict'>
{'site': 'A', 'flow': 2.3}

### Using *args and **kwargs together

A function can accept **both positional and keyword arguments**.

In [27]:
def example_function(*args, **kwargs):
    print("Positional arguments:", args)
    print("Keyword arguments:", kwargs)

example_function(1, 2, 3, name="River", pH=7.2)

Positional arguments: (1, 2, 3)
Keyword arguments: {'name': 'River', 'pH': 7.2}

**Important rule**

You MUST have positional arguments first. Because `**kwargs` captures all remaining keyword arguments, if you have positional arguments after keyword arguments, Python cannot determine whether a later parameter is for the positional argument, or the keyword argument.

In [28]:
# The following does not work
# def example_function(**kwargs, *args):
#     print("Positional arguments:", args)
#     print("Keyword arguments:", kwargs)

### Default Values in Functions

Functions can define **default values** for parameters.

A **default value** is used when the caller does not provide an argument.

Basic syntax:

```python
def function_name(parameter=default_value):
    code block
    return
```

If the argument is provided, Python uses the given value.
If not, Python uses the **default** value.

In [29]:
# Examples
def greet(name="Guest"):
    print("Hello,", name)

In [30]:
greet()

Hello, Guest

In [31]:
greet("Alice")

Hello, Alice

In [32]:
def convert_temperature(temp, unit="C"):
    if unit == "C":
        return temp * 9/5 + 32
    else:
        return temp

In [33]:
convert_temperature(25)

77.0

In [34]:
convert_temperature(25, "F")

25

In [35]:
def describe_sample(site="Unknown", pH=7.0, temperature=20):
    print("Site:", site)
    print("pH:", pH)
    print("Temperature:", temperature)

In [36]:
describe_sample()

Site: Unknown
pH: 7.0
Temperature: 20

In [37]:
describe_sample(site="River A", pH=7.2)

Site: River A
pH: 7.2
Temperature: 20

In [38]:
describe_sample(site="River A", temperature=25)

Site: River A
pH: 7.0
Temperature: 25

describe_sample(site="River A", pH=7.2)

**Important rule**

Non-default parameters MUST come before default parameters.

In [39]:
# This is correct
def example(a, b=2):
    pass
    return (a, b)

example(a=1)

(1, 2)

## Control Flows

**Control flow** is the order in which a program executes instructions.

By default, Python runs code **from top to bottom**.

In [40]:
a = 5
b = 3
print(a + b)

8

The code above runs in order:

1. assign `a`
2. assign `b`
3. print the result

Control flow statements allow Python to **change the normal order** by:

- making decisions
- repeating code
- stopping early
- skipping some steps

In other words, control flow determines:
- whether some code runs or not
- whether code repeats
- when a program stops or skips parts

### Decisions (conditional statements): `if`, `elif`, `else`

Conditional statements let the program make decisions.

In [41]:
pH = 5.8

if pH < 6.5:
    print("Acidic")
elif pH <= 8.5:
    print("Near neutral / typical range")
else:
    print("Basic")

Acidic

#### How it works

- `if` checks the first condition
- `elif` checks another condition if the first one is false
- `else` runs if none of the earlier conditions are true

In [42]:
temperature_C = 32

if temperature_C < 0:
    print("Freezing conditions")
elif temperature_C < 25:
    print("Moderate temperature")
else:
    print("Warm conditions")

Warm conditions

### Repetitions (loops)

#### `for` loop

A `for` loop repeats code for each item in a container.

In [43]:
rain_mm = [0.0, 5.2, 12.1, 3.4]

for value in rain_mm:
    print(value)

0.0
5.2
12.1
3.4

This loop runs once for each rainfall value.

In [44]:
sites = ["A", "B", "C"]

for site in sites:
    print("Monitoring site:", site)

Monitoring site: A
Monitoring site: B
Monitoring site: C

In [45]:
# Example: compute total rainfall using a loop
rain_mm = [0.0, 5.2, 12.1, 3.4]

total = 0

for value in rain_mm:
    total = total + value

print("Total rainfall =", total)

Total rainfall = 20.7

#### `while` loop

A `while` loop repeats as long as a condition stays true.

In [46]:
i = 0

while i < 5:
    print(i)
    i = i + 1

0
1
2
3
4

Be careful with `while` loops. If the condition never becomes false, the loop will never end.

In [47]:
count = 3

while count > 0:
    print("Countdown:", count)
    count -= 1

print("Done")

Countdown: 3
Countdown: 2
Countdown: 1
Done

### Early exit or skipping

Sometimes you may want a program to stop or skip part of a loop.

#### `break`

`break` stops the loop immediately.

In [48]:
for x in range(10):
    if x == 5:
        break
    print(x)

0
1
2
3
4

#### `continue`

`continue` skips the current iteration and moves to the next one.

In [49]:
rain_mm = [0.0, 5.2, -999, 3.4, 7.1]

for value in rain_mm:
    if value == -999:
        print("Missing value found, skipping")
        continue
    print("Rainfall:", value)

Rainfall: 0.0
Rainfall: 5.2
Missing value found, skipping
Rainfall: 3.4
Rainfall: 7.1

### `pass`

`pass` does nothing. It is often used as a temporary placeholder.

You can use `pass` when you want to leave part of the program unfinished for now.

In [50]:
value = 10

if value > 0:
    pass
else:
    print("This will not run")

### `return` (inside functions)

`return` ends a function and optionally sends back a value.

In [51]:
def classify_pH(pH):
    if pH < 6.5:
        return "Acidic"
    elif pH <= 8.5:
        return "Near neutral / typical range"
    else:
        return "Basic"

result = classify_pH(7.2)
print(result)

Near neutral / typical range

In [52]:
def mean_value(data):
    total = 0
    for value in data:
        total += value
    return total / len(data)

print(mean_value([1, 2, 3, 4]))

2.5

### Basic error handling: `try` / `except`

This allows a program to handle errors more elegantly.

In [53]:
try:
    x = 10 / 0
except:
    print("You cannot divide by zero.")

You cannot divide by zero.

In [54]:
values = ["3.2", "5.1", "bad_data", "4.8"]

for item in values:
    try:
        number = float(item)
        print("Converted:", number)
    except:
        print("Could not convert:", item)

Converted: 3.2
Converted: 5.1
Could not convert: bad_data
Converted: 4.8

### Summary Table

| Category | Statement | Purpose |
|---|---|---|
| Decision | `if`, `elif`, `else` | Run code conditionally |
| Repetition | `for`, `while` | Repeat code |
| Loop control | `break`, `continue` | Stop or skip inside loops |
| Placeholder | `pass` | Do nothing |
| Function control | `return` | Exit a function |
| Error handling | `try`, `except` | Handle errors |

For beginners, focus on these first:

- `if` → make decisions
- `for` → repeat over items
- `while` → repeat while a condition is true

Then learn:

- `break` / `continue`
- `return`
- `try` / `except`


## Suggested Exercises

1. Create a list of 10 numbers and compute the mean.  
2. Create a dictionary representing a water sample (site, pH, temperature).  
3. Use pandas to create a small dataset of river flows and compute the average.  
4. Write a function that converts temperature from °C to °F.