# Supplementary Module 2: NumPy and Pandas

<a target="_blank" href="https://colab.research.google.com/github/yalinli2/EnvEtools/blob/main/course_modules/S2_NumPy_and_pandas.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

<a target="_blank" href="https:///mybinder.org/v2/gh/yalinli2/EnvEtools/main?urlpath=%2Fdoc%2Ftree%2Fcourse_modules%S2F2_NumPy_and_pandas.ipynb">
  <img src="https://mybinder.org/badge_logo.svg" alt="Open In Binder"/>
</a>

NumPy and pandas are the two most common Python tools for data analysis:

- **NumPy** for numerical arrays and fast computations
- **pandas** for tabular data analysis

In scientific and engineering work:

- **NumPy** is useful when working with vectors, matrices, and numerical simulation
- **pandas** is useful when working with tables, spreadsheets, time series, and mixed data types

A common workflow is:

1. use **NumPy** for numerical calculations
2. use **pandas** to organize inputs and outputs in table form

## Learning goals

By the end of this notebook, you should be able to:

- create and inspect NumPy arrays
- perform array math and basic statistics
- understand indexing, slicing, and boolean filtering
- create pandas Series and DataFrames
- load, inspect, filter, sort, and summarize tabular data
- add new columns and group data
- export results to a file

In [1]:
import numpy as np
import pandas as pd

## NumPy

### Basics

In [2]:
# A Python list
py_list = [1, 2, 3, 4, 5]
print("Python list:", py_list)

# A NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("NumPy array:", arr)
print("Type:", type(arr))

Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

NumPy arrays are similar to lists, but they are designed for efficient numerical operations.

In [3]:
# Array properties
arr = np.array([10, 20, 30, 40, 50])

print("Array:", arr)
print("Number of dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Size:", arr.size)

Array: [10 20 30 40 50]
Number of dimensions: 1
Shape: (5,)
Data type: int32
Size: 5

In [4]:
# 2D arrays
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A)
print("Shape:", A.shape)
print("Rows, columns:", A.shape[0], A.shape[1])

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Rows, columns: 2 3

### Creating arrays

In [5]:
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
sequence = np.arange(0, 10, 2)
spaced = np.linspace(0, 1, 5)

print("zeros:\n", zeros)
print("\nones:\n", ones)
print("\nsequence:", sequence)
print("spaced:", spaced)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

sequence: [0 2 4 6 8]
spaced: [0.   0.25 0.5  0.75 1.  ]

`np.arange(start, stop, step)` creates evenly spaced values using a step size.

`np.linspace(start, stop, n)` creates a specified number of evenly spaced values.

### Array math

In [6]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

print("x + y =", x + y)
print("x - y =", x - y)
print("x * y =", x * y)
print("x / y =", x / y)
print("x ** 2 =", x ** 2)

x + y = [11 22 33 44]
x - y = [ -9 -18 -27 -36]
x * y = [ 10  40  90 160]
x / y = [0.1 0.1 0.1 0.1]
x ** 2 = [ 1  4  9 16]

In [7]:
# Scalar operations
print("x + 5 =", x + 5)
print("x * 3 =", x * 3)

x + 5 = [6 7 8 9]
x * 3 = [ 3  6  9 12]

NumPy performs these operations **elementwise**.

### Indexing and slicing

In [8]:
arr = np.array([5, 10, 15, 20, 25, 30])

print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice arr[1:4]:", arr[1:4])
print("Every other element:", arr[::2])

First element: 5
Last element: 30
Slice arr[1:4]: [10 15 20]
Every other element: [ 5 15 25]

In [9]:
A = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(A)
print("Element at row 1, col 2:", A[1, 2])
print("First row:", A[0, :])
print("Second column:", A[:, 1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at row 1, col 2: 60
First row: [10 20 30]
Second column: [20 50 80]

### Boolean filtering

In [10]:
arr = np.array([3, 7, 12, 18, 21, 25])

mask = arr > 15
print("Mask:", mask)
print("Values > 15:", arr[mask])

Mask: [False False False  True  True  True]
Values > 15: [18 21 25]

Boolean filtering is very useful in data cleaning and selection.

### Basic statistics

In [11]:
data = np.array([12, 15, 14, 10, 18, 20, 16])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Standard deviation:", np.std(data))
print("Sum:", np.sum(data))

Mean: 15.0
Median: 15.0
Min: 10
Max: 20
Standard deviation: 3.1622776601683795
Sum: 105

In [12]:
# Example: daily flow rates in m3/day
flow = np.array([120, 135, 128, 140, 150, 145, 138])

print("Average flow:", flow.mean())
print("Peak flow:", flow.max())
print("Days above 140:", flow[flow > 140])

Average flow: 136.57142857142858
Peak flow: 150
Days above 140: [150 145]

## pandas

### Basics

In [13]:
s = pd.Series([10, 20, 30, 40], name="value")
print(s)

0    10
1    20
2    30
3    40
Name: value, dtype: int64

A **Series** is a one-dimensional labeled object.

A **DataFrame** is a two-dimensional labeled table.

In [14]:
df = pd.DataFrame({
    "site": ["A", "B", "C", "D"],
    "flow_m3_day": [120, 150, 90, 200],
    "ph": [7.1, 6.8, 7.4, 7.0]
})

df

  site  flow_m3_day   ph
0    A          120  7.1
1    B          150  6.8
2    C           90  7.4
3    D          200  7.0

### Inspecting a DataFrame

In [15]:
print(df.head())
print()
print(df.tail())
print()
print(df.info())
print()
print(df.describe())

  site  flow_m3_day   ph
0    A          120  7.1
1    B          150  6.8
2    C           90  7.4
3    D          200  7.0

  site  flow_m3_day   ph
0    A          120  7.1
1    B          150  6.8
2    C           90  7.4
3    D          200  7.0

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   site         4 non-null      str
 1   flow_m3_day  4 non-null      int64
 2   ph           4 non-null      float64
dtypes: float64(1), int64(1), str(1)
memory usage: 228.0 bytes
None

       flow_m3_day     ph
count     4.000000  4.000
mean    140.000000  7.075
std      46.904158  0.250
min      90.000000  6.800
25%     112.500000  6.950
50%     135.000000  7.050
75%     162.500000  7.175
max     200.000000  7.400

In [16]:
print("Column names:", df.columns.tolist())
print("Shape:", df.shape)

Column names: ['site', 'flow_m3_day', 'ph']
Shape: (4, 3)

### Selecting columns and rows

In [17]:
print(df["site"])
print()
print(df[["site", "flow_m3_day"]])

0    A
1    B
2    C
3    D
Name: site, dtype: str

  site  flow_m3_day
0    A          120
1    B          150
2    C           90
3    D          200

In [18]:
print(df.loc[0])      # label-based row selection
print()
print(df.iloc[1:3])   # position-based row selection

site             A
flow_m3_day    120
ph             7.1
Name: 0, dtype: object

  site  flow_m3_day   ph
1    B          150  6.8
2    C           90  7.4

### Filtering data

In [19]:
high_flow = df[df["flow_m3_day"] > 120]
high_flow

  site  flow_m3_day   ph
1    B          150  6.8
3    D          200  7.0

In [20]:
neutral_or_higher = df[df["ph"] >= 7.0]
neutral_or_higher

  site  flow_m3_day   ph
0    A          120  7.1
2    C           90  7.4
3    D          200  7.0

### Adding new columns

In [21]:
df["flow_L_day"] = df["flow_m3_day"] * 1000
df["flow_category"] = np.where(df["flow_m3_day"] >= 130, "high", "low")
df

  site  flow_m3_day   ph  flow_L_day flow_category
0    A          120  7.1      120000           low
1    B          150  6.8      150000          high
2    C           90  7.4       90000           low
3    D          200  7.0      200000          high

### Sorting

In [22]:
df.sort_values("flow_m3_day", ascending=False)

  site  flow_m3_day   ph  flow_L_day flow_category
3    D          200  7.0      200000          high
1    B          150  6.8      150000          high
0    A          120  7.1      120000           low
2    C           90  7.4       90000           low

### Grouping and aggregation

In [23]:
df2 = pd.DataFrame({
    "plant": ["North", "North", "South", "South", "South"],
    "month": ["Jan", "Feb", "Jan", "Feb", "Mar"],
    "flow_m3_day": [100, 120, 80, 95, 110]
})

df2

   plant month  flow_m3_day
0  North   Jan          100
1  North   Feb          120
2  South   Jan           80
3  South   Feb           95
4  South   Mar          110

In [24]:
df2.groupby("plant")["flow_m3_day"].mean()

plant
North    110.0
South     95.0
Name: flow_m3_day, dtype: float64

In [25]:
df2.groupby("plant").agg({
    "flow_m3_day": ["mean", "max", "min"]
})

      flow_m3_day
             mean  max  min
plant
North       110.0  120  100
South        95.0  110   80

### Missing values

In [26]:
df_missing = pd.DataFrame({
    "site": ["A", "B", "C", "D"],
    "bod_mg_L": [210, np.nan, 180, 195],
    "tss_mg_L": [120, 115, np.nan, 130]
})

df_missing

  site  bod_mg_L  tss_mg_L
0    A     210.0     120.0
1    B       NaN     115.0
2    C     180.0       NaN
3    D     195.0     130.0

In [27]:
print(df_missing.isna().sum())
print()
print(df_missing.dropna())
print()
print(df_missing.fillna(df_missing.mean(numeric_only=True)))

site        0
bod_mg_L    1
tss_mg_L    1
dtype: int64

  site  bod_mg_L  tss_mg_L
0    A     210.0     120.0
3    D     195.0     130.0

  site  bod_mg_L    tss_mg_L
0    A     210.0  120.000000
1    B     195.0  115.000000
2    C     180.0  121.666667
3    D     195.0  130.000000

### Reading and writing files

In [28]:
# Save a CSV file
df.to_csv("example_sites.csv", index=False)

# Read it back
df_loaded = pd.read_csv("example_sites.csv")
df_loaded

  site  flow_m3_day   ph  flow_L_day flow_category
0    A          120  7.1      120000           low
1    B          150  6.8      150000          high
2    C           90  7.4       90000           low
3    D          200  7.0      200000          high

### Using NumPy and pandas together

In [29]:
np.random.seed(42)

measurements = np.random.normal(loc=50, scale=5, size=20)

data_df = pd.DataFrame({
    "sample_id": range(1, 21),
    "measurement": measurements
})

data_df["above_mean"] = data_df["measurement"] > data_df["measurement"].mean()
data_df.head()

   sample_id  measurement  above_mean
0          1    52.483571        True
1          2    49.308678        True
2          3    53.238443        True
3          4    57.615149        True
4          5    48.829233       False

In [30]:
print("Mean measurement:", data_df["measurement"].mean())
print("Standard deviation:", data_df["measurement"].std())

Mean measurement: 49.14350719279086
Standard deviation: 4.800142107195134

## Exercises

Try editing the examples above:

1. change the array values and recompute the statistics
2. add another column to the DataFrame
3. filter rows using two conditions
4. group by a different category
5. save a table and open it in Excel